# Generated by Django 3.0.6 on 2020-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512, verbose_name='Путь к csv-файлу')),
            ],
            options={
                'verbose_name': 'Путь к csv-файлу',
                'verbose_name_plural': 'Путь к csv-файлу',
            },
        ),
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя столбца')),
                ('width', models.IntegerField(default=10, verbose_name='Ширина столбца')),
                ('serial', models.IntegerField(default=1, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблица',
            },
        ),
    ]
