# Generated by Django 3.0.6 on 2020-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20200530_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablefield',
            name='width',
            field=models.IntegerField(default=10, verbose_name='Ширина столбца'),
        ),
    ]
