# Generated by Django 3.0.6 on 2020-06-04 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Станции и маршруты',
                'verbose_name_plural': 'Станции и маршруты',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=128)),
                ('routes', models.ManyToManyField(related_name='stations', through='project.Relationship', to='project.Route')),
            ],
            options={
                'verbose_name': 'Автобусная остановка',
                'verbose_name_plural': 'Автобусные остановки',
            },
        ),
        migrations.AddField(
            model_name='relationship',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Route'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Station'),
        ),
    ]
