# Generated by Django 3.0.6 on 2020-06-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relationship',
            new_name='StationRoute',
        ),
    ]
