# Generated by Django 3.0.6 on 2020-06-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200530_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
